version: '3.3'

services:

  node6:
    image: node:6.11.3
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules:cached
    working_dir: "/app"
    tty: true

  node8:
    image: node:8.4.0
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules:cached
    working_dir: "/app"
    tty: true